### ISSUE TITLE
erreur if i want install new project in dazzle

### ISSUE THREAD

**Issue by bilhack** [hbons/Dazzle#28]
hi i get this erreur if i want make new project.

(i used redhat os in virtual machine)

[root@localhost ~]# dazzle create PROJECT_NAME
which: no git in (/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin)
Creating project "PROJECT_NAME"...
  ->  init --bare /var/lib/stuff/PROJECT_NAME
init: invalid option: --bare
Try `init --help' for more information.
  ->  config --file /var/lib/stuff/PROJECT_NAME/config receive.denyNonFastForwards true
/usr/bin/dazzle: line 168: config: command not found
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 175: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory
/usr/bin/dazzle: line 179: /var/lib/stuff/PROJECT_NAME/info/attributes: No such file or directory

  -> chown --recursive dazzle:dazzle /var/lib/stuff
chown: invalid user: `dazzle:dazzle'
  -> chmod --recursive o-rwx /var/lib/stuff/PROJECT_NAME
chmod: cannot access`/var/lib/stuff/PROJECT_NAME': No such file or directory

**Comment by vlaube-de** [comment]
I can confirm that this is what happen whe git is not installed. "dazzle create" calls "$GIT init" but $GIT is an empty string so "init" gets called,
The pull request #44 that was just merged into master fixes this by checking if git is actually installed.

@hbons: this issue can be closed
