### ISSUE TITLE
dazzle readme needs to be updated

### ISSUE THREAD

**Issue by kjyv** [hbons/Dazzle#41]
Installing dazzle as the readme says using "dazzle setup" will not properly do the setup as the user "" is used. After adding -u storage and deleting /home/.ssh I thought I was ok. However, a faulty entry in sshd_config also prevented ssh from starting at boot, locking me out. You definitely need to fix something (the readme or the defaults not being used) as this is potentially dangerous!

**Comment by EugeneTM** [comment]
DAZZLE_USER is empty in the script.

**Comment by hbons** [comment]
Fixed by #43.
